version: '3.8'
services:
  api:
    container_name: node_api
    restart: on-failure
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - "4000:4000"
    command: >
      sh -c "yarn start"
  test:
    container_name: node_api_test
    restart: on-failure
    build: .
    volumes:
      - ./src:/app/src
    entrypoint: sh -c "yarn test"      
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:


